# Generated by Django 3.2 on 2021-06-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('vaccines', '__first__'),
        ('posto', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(max_length=200, verbose_name='Observação')),
                ('date_vaccination', models.DateField(verbose_name='Data de Aplicação')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.posto')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinacao',
                'ordering': ['id'],
            },
        ),
    ]
